sudo: required
services:
  - docker

before_install:
  - docker build -t gabrieldevareilles/docker-react -f Dockerfile.dev .

script:
  - docker run gabrieldevareilles/docker-react npm run test -- --coverage
